### ISSUE TITLE
Invalid protocol: xfinityhome error.

### ISSUE THREAD

**Issue by emmcc** [nfarina/homebridge-icontrol#3]
I'm receiving the following error when running homebridge. Any ideas what might be causing it?

> [Xfinity Home] There was an error while communicating with iControl. Status code was undefined and error was: Error: Invalid protocol: xfinityhome:

Here are the surrounding logs:

>   iControl Logging in with authorization code from web form... +549ms
  iControl Access token expired; logging in again... +532ms
  iControl Redirected to https://login.comcast.net/login?r=comcast.net&s=oauth&continue=https%3A%2F%2Flogin.comcast.net%2Foauth%2Fauthorize%3Fclient_id%3DXfinity-Home-iOS-App%26response_type%3Dcode%26redirect_uri%3Dxfinityhome%253A%252F%252Fauth%26response%3D1&reqId=7b842800-d039-448a-ae86-9a5459cb4e69&client_id=Xfinity-Home-iOS-App +111ms
[7/12/2017, 3:21:00 PM] [Xfinity Home] There was an error while communicating with iControl. Status code was undefined and error was: Error: Invalid protocol: xfinityhome:
Stack:Error
    at iControl._notifyError (/usr/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:500:181)
    at iControl.<anonymous> (/usr/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:233:16)
    at self.callback (/usr/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.init (/usr/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:460:17)
    at Redirect.onResponse (/usr/lib/node_modules/homebridge-icontrol/node_modules/request/lib/redirect.js:152:11)
    at Request.onRequestResponse (/usr/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:996:22)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
Response:
undefined

**Comment by fitzage** [comment]
I'm having this problem as well when trying to run homebridge on macOS.

I see this is over a month old. @emmcc did you find a solution?

**Comment by ghost** [comment]
I'm having the same issue. Any advice? 

Thanks,
ayanm00

**Comment by nfarina** [comment]
Sorry guys, this plugin has been broken for a while. Xfinity seems to have made changes to their API and the `node-icontrol` library needs to be updated to deal with that. If anyone wants to make a PR to fix it, I would welcome it!
